# Generated by Django 5.1 on 2024-09-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('caretaker', 'Caretaker')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_regid', models.CharField(max_length=100, unique=True)),
                ('org_email', models.EmailField(max_length=254, unique=True)),
                ('org_name', models.CharField(max_length=100)),
                ('org_address', models.TextField()),
                ('org_phone', models.CharField(max_length=12)),
                ('org_password', models.CharField(default='defaultpassword', max_length=128)),
                ('approve', models.BooleanField(default=False)),
                ('pincode', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='organization_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='organization_set', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
    ]
