# Generated by Django 5.1 on 2024-10-24 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organizations'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organizations'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='org_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organizations'),
        ),
    ]
