# Generated by Django 5.1 on 2025-01-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicerequest_phone_teamvisit_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamdashboard',
            options={},
        ),
        migrations.RemoveField(
            model_name='teamdashboard',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='teamdashboard',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teamdashboard',
            name='username',
        ),
        migrations.AddField(
            model_name='teamdashboard',
            name='role',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamdashboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teamdashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teamdashboard',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='teamdashboard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team'),
        ),
    ]
