# Generated by Django 5.1 on 2024-09-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_palliativeorganization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palliativeorganization',
            name='about',
        ),
        migrations.RemoveField(
            model_name='palliativeorganization',
            name='city',
        ),
        migrations.RemoveField(
            model_name='palliativeorganization',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='palliativeorganization',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='palliativeorganization',
            name='services',
        ),
        migrations.RemoveField(
            model_name='palliativeorganization',
            name='state',
        ),
        migrations.RemoveField(
            model_name='palliativeorganization',
            name='website',
        ),
        migrations.AddField(
            model_name='palliativeorganization',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='palliativeorganization',
            name='registration_certificate',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AlterField(
            model_name='palliativeorganization',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
