# Generated by Django 5.1.6 on 2025-03-17 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizations_latitude_organizations_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisitrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamvisit',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teamvisit',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teamvisit'),
        ),
        migrations.AlterField(
            model_name='teamvisit',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20),
        ),
    ]
