# Generated by Django 5.1 on 2024-09-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memb_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
                ('memb_photo', models.ImageField(upload_to='team_photos/')),
                ('memb_email', models.EmailField(max_length=255, unique=True)),
                ('memb_phone', models.CharField(max_length=15, unique=True)),
                ('org_regid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizations')),
            ],
            options={
                'db_table': 'OrgTeamMember',
            },
        ),
    ]
