# Generated by Django 5.1 on 2024-12-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notificationpreferences_privacysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammessage',
            name='sender_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('organization', 'Organization')], default='staff', max_length=20),
        ),
    ]
