# Generated by Django 5.1 on 2024-10-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teamvisitrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamvisitrequest',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teamvisitrequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
