# Generated by Django 5.1 on 2024-09-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_orgteammember'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orgteammember',
            table='OrgTeamMember',
        ),
    ]
