# Generated by Django 5.1 on 2024-09-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_palliativeorganization_about_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PalliativeOrganization',
        ),
    ]
