# Generated by Django 5.1.6 on 2025-03-17 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_patientvisitrecord_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisitrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamvisit',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamvisit',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='accounts.teamvisit'),
        ),
        migrations.AlterField(
            model_name='teamvisit',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='RentalExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_days', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='accounts.equipmentrental')),
            ],
        ),
    ]
