# Generated by Django 5.1 on 2024-10-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staff_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('VOLUNTEER', 'Volunteer')], max_length=10),
        ),
    ]
