# Generated by Django 5.1 on 2025-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patientvisitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisitrecord',
            name='activity_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Bedbound'), (2, 'Wheelchair bound'), (3, 'Walks with assistance'), (4, 'Walks independently')], null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='appetite',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good')], null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='consciousness_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='deterioration_risk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='fall_risk_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='mood_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Depressed'), (2, 'Anxious'), (3, 'Normal'), (4, 'Elevated')], null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='next_visit_recommendation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='overall_health_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='pain_character',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='pressure_ulcer_risk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='visit_priority_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
