# Generated by Django 5.1 on 2024-11-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teamvisitrequest_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
