# Generated by Django 5.1 on 2024-12-16 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teammessage_sender_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='teammessage',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='team_messages/'),
        ),
        migrations.AddField(
            model_name='teammessage',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General Communication'), ('PATIENT_UPDATE', 'Patient Update'), ('VISIT_REPORT', 'Visit Report'), ('EMERGENCY', 'Emergency')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='teammessage',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammessage',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_messages', to='accounts.organizations'),
        ),
    ]
