# Generated by Django 5.1.6 on 2025-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_equipmentrental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrental',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('END', 'Ended'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
