# Generated by Django 5.1 on 2025-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patientvisitrecord_activity_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisitrecord',
            name='pain_character',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisitrecord',
            name='pain_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
