# Generated by Django 5.1 on 2024-10-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('STAFF', 'Staff')], default='PATIENT', max_length=10),
        ),
    ]
