# Generated by Django 5.1 on 2024-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_role_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_username', models.CharField(max_length=100)),
                ('org_email', models.EmailField(max_length=254)),
                ('org_name', models.CharField(max_length=100)),
                ('org_address', models.TextField(verbose_name=100)),
                ('org_phone', models.CharField(max_length=12)),
                ('org_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('caretaker', 'Caretaker')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
