# Generated by Django 5.1 on 2025-02-11 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organizations_latitude_organizations_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('patient', 'Patient'), ('caretaker', 'Caretaker')], default='patient', max_length=10),
        ),
        migrations.CreateModel(
            name='CaretakerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
