# Generated by Django 5.1 on 2024-09-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organizations_user_role_delete_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='org_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='org_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='org_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='org_username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
