# Generated by Django 5.1 on 2024-12-16 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teamnotification_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='teammessage',
            name='patient',
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.organizations'),
        ),
        migrations.DeleteModel(
            name='TeamNotification',
        ),
    ]
