# Generated by Django 5.1.6 on 2025-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_equipmentrental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Payment'), ('RENTAL_BILL', 'Rental Bill'), ('REFUND', 'Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
