# Generated by Django 5.1 on 2025-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_patient_name_user_usertype_caretakerdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisitrecord',
            name='priority_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisitrecord',
            name='priority_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
