# Generated by Django 5.1 on 2024-10-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_user_type_alter_staff_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientassignment',
            name='last_interaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientassignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
