# Generated by Django 5.1 on 2024-10-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_organizations_groups_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='user',
        ),
        migrations.AddField(
            model_name='organizations',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='organization_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='organization_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='org_password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='org_phone',
            field=models.CharField(max_length=12),
        ),
    ]
