# Generated by Django 5.1 on 2024-10-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_organizations_user_organizations_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgteammember',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
