# Generated by Django 5.1.6 on 2025-03-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_patientlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvisitrecord',
            options={},
        ),
        migrations.AlterField(
            model_name='patientvisitrecord',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='patientvisitrecord',
            name='priority_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PatientLocation',
        ),
    ]
