# Generated by Django 5.1 on 2024-12-17 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_team_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamdashboard',
            options={'verbose_name': 'Team Dashboard', 'verbose_name_plural': 'Team Dashboards'},
        ),
        migrations.AddField(
            model_name='teamdashboard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teamdashboard',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamdashboard',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_dashboards', to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='teamdashboard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='accounts.team'),
        ),
    ]
