# Generated by Django 5.1 on 2024-10-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_orgteammember_employee_id'),
    ]

    operations = [
    ]
