# Generated by Django 5.1 on 2025-02-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_medicalequipment_image_equipmentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalequipment',
            old_name='image',
            new_name='primary_image',
        ),
        migrations.AddField(
            model_name='medicalequipment',
            name='additional_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='EquipmentImage',
        ),
    ]
