# Generated by Django 5.1 on 2024-10-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_populate_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgteammember',
            name='org_regid',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='OrgTeamMember',
        ),
    ]
