# Generated by Django 4.1.13 on 2024-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_userprofile_user_delete_customuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('caretaker', 'Caretaker')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
