# Generated by Django 5.1 on 2025-02-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_image_medicalequipment_primary_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentrental',
            old_name='security_deposit',
            new_name='daily_rental_price',
        ),
        migrations.RenameField(
            model_name='equipmentrental',
            old_name='total_amount',
            new_name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='equipmentrental',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='equipmentrental',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='equipmentrental',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='equipmentrental',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='equipmentrental',
            name='start_date',
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='rental_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='rental_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
