# Generated by Django 5.1 on 2024-10-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_appointment_cancellation_reason_appointment_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
    ]
