# Generated by Django 5.1 on 2025-02-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_security_deposit_equipmentrental_daily_rental_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrental',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
