# Generated by Django 4.1.13 on 2024-09-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_patient_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizations',
            old_name='org_username',
            new_name='org_regid',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='password',
        ),
        migrations.AddField(
            model_name='organizations',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizations',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
