# Generated by Django 5.1 on 2024-10-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_servicerequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
