# Generated by Django 5.1 on 2024-10-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_servicerequest_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='rejection_reason',
        ),
    ]
