# Generated by Django 5.1 on 2025-02-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_equipmentrental_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentrental',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='equipmentrental',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='equipmentrental',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('INITIAL', 'Initial Payment'), ('EXTENSION', 'Rental Extension'), ('DAMAGE', 'Damage Charges'), ('REFUND', 'Security Deposit Refund')], max_length=20)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], max_length=20)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.equipmentrental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalPaymentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_payments', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('security_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rental_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunds_issued', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organizations')),
            ],
            options={
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
