# Generated by Django 5.1 on 2024-10-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_notification_message_team_teamvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamvisit',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='accounts.teamvisit'),
        ),
        migrations.AddField(
            model_name='teamvisit',
            name='rescheduled_reason',
            field=models.TextField(blank=True),
        ),
    ]
