# Generated by Django 5.1 on 2024-10-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizations',
            old_name='org_email',
            new_name='email',
        ),
    ]
