# Generated by Django 5.1 on 2025-02-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_equipmentrental_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalequipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units available'),
        ),
    ]
