# Generated by Django 5.1 on 2024-10-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_org_email_organizations_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizations',
            old_name='email',
            new_name='org_email',
        ),
    ]
