# Generated by Django 5.1 on 2024-10-20 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_teammessage_visitchecklist_visitnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammessage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.organizations'),
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.staff'),
        ),
    ]
