# Generated by Django 5.1 on 2025-02-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_medicalequipment_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentdelivery',
            old_name='delivery_date',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='equipmentdelivery',
            name='signature_image',
        ),
        migrations.AddField(
            model_name='equipmentdelivery',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdelivery',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.equipmentrental'),
        ),
        migrations.AlterField(
            model_name='equipmentdelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentdelivery',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff'),
        ),
    ]
