# Generated by Django 5.1 on 2024-10-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_teammessage_organization_alter_teammessage_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TeamDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='accounts.team')),
            ],
        ),
    ]
