# Generated by Django 5.1 on 2024-10-20 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_teammessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdashboard',
            name='created_at',
        ),
        migrations.AddField(
            model_name='teamdashboard',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamdashboard',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdashboard',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.team'),
        ),
    ]
