# Generated by Django 5.1 on 2024-10-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_teamdashboard_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdashboard',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='teamdashboard',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='teamdashboard',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
