# Generated by Django 5.1 on 2025-03-02 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_monthlyrentalpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyrentalpayment',
            options={'ordering': ['-month_start_date']},
        ),
        migrations.RenameField(
            model_name='monthlyrentalpayment',
            old_name='month_year',
            new_name='month_end_date',
        ),
        migrations.RenameField(
            model_name='monthlyrentalpayment',
            old_name='payment_deadline',
            new_name='month_start_date',
        ),
        migrations.RemoveField(
            model_name='monthlyrentalpayment',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='monthlyrentalpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyrentalpayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyrentalpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monthlyrentalpayment',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RentalUsagePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_periods', to='accounts.equipmentrental')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
