# Generated by Django 5.1 on 2024-10-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_teamdashboard_staff_alter_teamdashboard_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdashboard',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
        migrations.AlterField(
            model_name='teamdashboard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teamdashboard',
            unique_together={('team', 'staff')},
        ),
    ]
