# Generated by Django 5.1 on 2025-03-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_monthlyrentalpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deterioration_risk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='fall_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='overall_health_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='visit_priority_score',
            field=models.FloatField(default=0.0),
        ),
    ]
