# Generated by Django 5.1 on 2025-03-02 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_deterioration_risk_user_fall_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisitrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
