# Generated by Django 5.1 on 2025-03-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_patientvisitrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_known_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_known_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
