# Generated by Django 5.1 on 2025-03-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_staff_last_known_latitude_staff_last_known_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='last_known_latitude',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_known_longitude',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_location_update',
        ),
    ]
