# Generated by Django 5.1.6 on 2025-03-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_teammessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffonlinestatus',
            name='staff',
        ),
        migrations.AlterModelOptions(
            name='teammessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='teammessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.organizations'),
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.staff'),
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
        migrations.DeleteModel(
            name='StaffOnlineStatus',
        ),
    ]
