# Generated by Django 5.1.6 on 2025-03-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
